language: python

python:
  # - 3.9
  - 3.8
  - 3.7

install:
  - pip install -r requirements.txt

script:
  - python -m pytest
  - flake8 --exclude env --ignore E402,E501 .
  - black --exclude=env .
